<<<<<<< HEAD
<<<<<<< HEAD
=======
markdown: kramdown
>>>>>>> bc27370ec43c2839542bc57e10d4d809afe7c8fc
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
=======
theme: jekyll-theme-architect
<<<<<<< HEAD
=======
markdown: kramdown
>>>>>>> bc27370ec43c2839542bc57e10d4d809afe7c8fc
>>>>>>> 82dca19eba3e0e93631101d1e7413987cea338f5
